services:
    app:
        env_file:
            - .env
        image: hw16_docker:dev
        container_name: app
        ports:
            - ${APP_HTTP_PORT}:8080
        links:
            - pg-storage
        depends_on:
            - pg-storage

    pg-storage:
        env_file:
            - .env
        image: postgres:16.2-alpine
        container_name: pg-storage
        environment:
            POSTGRES_DB: ${APP_DB_DATABASE}
            POSTGRES_USER: ${APP_DB_USER}
            POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./localdata/pg-storage:/var/lib/postgresql/data
        ports:
            - ${APP_DB_PORT}:5432
    
    # migrator:
    #     env_file:
    #         - .env
    #     image: golang:1.23.1
    #     build:
    #         dockerfile: Migration_Dockerfile
    #     container_name: migrator
    #     links:
    #         - pg-storage
    #     depends_on:
    #         - pg-storage


